CREATE TABLE IF NOT EXISTS students (
    id SERIAL PRIMARY KEY,
    nim VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    grade DOUBLE PRECISION NOT NULL CHECK (grade >= 0.0 AND grade <= 4.0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS students_name_idx
ON students (LOWER(name));
